
  // DO NOT MODIFY. This file is automatically generated by the test suite.

  
  import { mongooseAdapter } from '@payloadcms/db-mongodb'

  export const databaseAdapter = mongooseAdapter({
    // In integration tests we frequently drop/recreate DBs and start multiple
    // Payload instances. Automatic index builds can cause transient catalog
    // change errors in Mongo (especially in in-memory replica sets).
    ensureIndexes: false,
    url:
      process.env.MONGODB_MEMORY_SERVER_URI ||
      process.env.DATABASE_URI ||
      'mongodb://127.0.0.1/payloadtests',
  })
  